name = "foreveryoung"
pages_build_output_dir = "."
compatibility_date = "2024-06-07"

[[d1_databases]]
binding = "DB"
database_name = "foreveryoung-db"
database_id = "93ac3813-324e-4ee5-b6d8-68f31955e06b"
remote = true

[ai]
binding = "AI"